name: epub wandering_inn_vol_1-8

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v3
      - name: Checkout submodules
        run: git submodule update --init --recursive
    
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Setup Python requirements
        run: python -m pip install -r requirements.txt           
        
      - name: Generate epub
        run: python ./wanderinginn2epub.py --volume 1 2 3 4 5 6 7 8 --strip-color

      - name: 'Upload epub'
        uses: actions/upload-artifact@v3.1.0
        with:
          name: wandering_inn_vol_1-8          
