name: generate epub

on:
  workflow_dispatch:

jobs:
  build:    
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Python requirements
        run: |       
          python -m pip install --upgrade pip setuptools wheel          
          python -m pip install -r requirements.txt          
          python -m pip install ebookmaker bs4
        
      - name: Generate
        run: |       
          chmod +x wanderinginn2epub.py
          python ./wanderinginn2epub.py --volume 1 2 3 4 5 6 7 8 --output-by-volume  --strip-color

      - name: 'Upload a Build Artifact'
        uses: actions/upload-artifact@v3.1.0
